services:
  database:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./apps/backend
    environment:
      DATABASE_URL: postgres://multitune:multitune@database:5432/multitune
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./apps/frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: