version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: multitune
      POSTGRES_PASSWORD: multitune
      POSTGRES_DB: multitune
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U multitune"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
