name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multitune-backend:latest
      - name: Create frontend .env file
        run: |
          echo 'VITE_BACKEND_HOST="${{ secrets.VITE_BACKEND_HOST }}"' > apps/frontend/.env
          echo 'VITE_BACKEND_PORT="${{ secrets.VITE_BACKEND_PORT }}"' >> apps/frontend/.env
          cat apps/frontend/.env
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./apps/frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multitune-frontend:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Placeholder test step
        run: echo "No tests yet, but this is where they'd go."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/multitune/multitune/
            git pull origin main
            docker-compose pull
            docker-compose down
            docker-compose up -d