name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multitune-backend:latest
      - name: Create frontend .env file
        run: |
          echo "VITE_BACKEND_HOST=${{ secrets.VITE_BACKEND_HOST }}" > apps/frontend/.env
          echo "VITE_BACKEND_PORT=${{ secrets.VITE_BACKEND_PORT }}" >> apps/frontend/.env
          cat apps/frontend/.env
      - name: Check .env exists and is not empty
        run: |
          ls -l apps/frontend/.env
          wc -l apps/frontend/.env
          head -n 5 apps/frontend/.env
          cat apps/frontend/.env
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./apps/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multitune-frontend:latest
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/multitune/multitune/
            git pull origin main
            docker-compose pull
            docker-compose down
            docker-compose up -d